//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string Answer { get; set; }
        public string Type { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
